### ISSUE TITLE
fix: An unhandled exception occurred: MissingPluginException(No implementation found for method connect on channel flutter_blue_plus/methods)

### ISSUE THREAD

**Issue by vontdeux** [chan150/flutter_blue_plus_windows#21]
**Description**

**Steps To Reproduce**

Follow connect instruction on flutter_blue_plus

```
try {
      //create device var
      var device = BluetoothDevice.fromId(deviceId);
      //connect
      await device.connect();
      } catch (e) {
      print('An unhandled exception occurred: $e');
      return false;
    }
```

**Expected Behavior**

device will connect like on mobile (this code works on mobile)

**Screenshots**

**Additional Context**

**Comment by chan150** [comment]
It may work in `1.24.16`.

**Comment by chan150** [comment]
If you want to BluetoothDevice in `flutter_blue_plus_windows`,
please use `BluetoothDeviceWindows.fromId` instead of `BluetoothDevice.fromId`.

It may work in `1.24.17`.
