### ISSUE TITLE
fix: subscribe to characteristics does not behave like it should

### ISSUE THREAD

**Issue by vontdeux** [chan150/flutter_blue_plus_windows#22]
**Description**

on flutter_blue_plus(FBP) and win_ble, subscribing to a characteristic of a device will response with value everytime a write to characteristic is sent

**for example in FBP**
```
final subscription = characteristic.onValueReceived.listen((value) {
    // onValueReceived is updated:
    //   - anytime read() is called
    //   - anytime a notification arrives (if subscribed)
});

// cleanup: cancel subscription when disconnected
device.cancelWhenDisconnected(subscription);

// subscribe
// Note: If a characteristic supports both **notifications** and **indications**,
// it will default to **notifications**. This matches how CoreBluetooth works on iOS.
await characteristic.setNotifyValue(true);
```

**win_ble**
  `await WinBle.subscribeToCharacteristic(address: address, serviceId: serviceID, characteristicId: charID);`

**and when sending a write (FBP)**
```
await c.write([0x12, 0x34]);

final subscription = characteristic.onValueReceived.listen((value) {
//    onValueReceived here will receive a response from the bluetooth device
// print value
print(value);
//output - "[1,2,3,4]"
});
```

but instead of a correct response from the device, flutter_blue_plus_windows will just copy the value it was last written as a value response
**flutter_blue_plus_windows**
```
await c.write([0x12, 0x34]);

final subscription = characteristic.onValueReceived.listen((value) {
//    onValueReceived here will receive a response from the bluetooth device
// print value
print(value);
//output - "[0x12, 0x34]"
});
```

**Steps To Reproduce**

1. connect a device
2. set subscription with notify true
3. write to device's characteristics
4. print the onValueReceived's value

**Expected Behavior**

an correct response from bluetooth device

**Screenshots**

**Additional Context**

**Comment by chan150** [comment]
It may be fixed in `1.24.19`.
