### ISSUE TITLE
fix: Project run failed

### ISSUE THREAD

**Issue by shplume** [chan150/flutter_blue_plus_windows#24]
**Description**

**Steps To Reproduce**

I installed this library, but after that my project could not run. 

**Expected Behavior**

The project is running normally.

**Screenshots**

![image](https://github.com/user-attachments/assets/29f60d9c-a47f-478c-b1a3-31ffc5842484)

**Additional Context**

Flutter 3.24.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 603104015d (2 weeks ago) • 2024-10-24 08:01:25 -0700
Engine • revision db49896cf2
Tools • Dart 3.5.4 • DevTools 2.37.3

flutter_blue_plus_windows: ^1.24.19

  flutter_blue_plus:
    dependency: transitive
    description:
      name: flutter_blue_plus
      sha256: "160ddacb839b244f86e96fbee7e9a823e5caf1b046ccf1f0a7901f9d5aa39eb9"
      url: "https://pub.dev"
    source: hosted
    version: "1.34.4"
  flutter_blue_plus_windows:
    dependency: "direct main"
    description:
      name: flutter_blue_plus_windows
      sha256: "1a0877425a9872ab86569a84a99591dc8e9edd67cc280b57cb5a44970d1e070a"
      url: "https://pub.dev"
    source: hosted
    version: "1.24.19"

**Comment by leelizk** [comment]
> **Description**
> 
> A clear and concise description of what the bug is.
> 
> **Steps To Reproduce**
> 
> I installed this library, but after that my project could not run.
> 
> **Expected Behavior**
> 
> The project is running normally.
> 
> **Screenshots**
> 
> ![image](https://private-user-images.githubusercontent.com/72640912/384674715-29f60d9c-a47f-478c-b1a3-31ffc5842484.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyNTkzMjgsIm5iZiI6MTczMTI1OTAyOCwicGF0aCI6Ii83MjY0MDkxMi8zODQ2NzQ3MTUtMjlmNjBkOWMtYTQ3Zi00NzhjLWIxYTMtMzFmZmM1ODQyNDg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEwVDE3MTcwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1YzA2YWU4NDU0NWU0MWQyZTZkMTdjYjA4ODBjZjY2MGNkZGY5NGM4ZjdjNGI2MjEzODk1NTA4OWQ0OWZlN2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.GkXqwinssC_w3gMmPGx4Tboduy7KQq6lNb0L6UxKzDk)
> 
> **Additional Context**
> 
> Flutter 3.24.4 • channel stable • https://github.com/flutter/flutter.git Framework • revision 603104015d (2 weeks ago) • 2024-10-24 08:01:25 -0700 Engine • revision db49896cf2 Tools • Dart 3.5.4 • DevTools 2.37.3
> 
> flutter_blue_plus_windows: ^1.24.19
> 
> flutter_blue_plus: dependency: transitive description: name: flutter_blue_plus sha256: "160ddacb839b244f86e96fbee7e9a823e5caf1b046ccf1f0a7901f9d5aa39eb9" url: "https://pub.dev" source: hosted version: "1.34.4" flutter_blue_plus_windows: dependency: "direct main" description: name: flutter_blue_plus_windows sha256: "1a0877425a9872ab86569a84a99591dc8e9edd67cc280b57cb5a44970d1e070a" url: "https://pub.dev" source: hosted version: "1.24.19"

this issue cause by  flutter blue plus version does not match . downgrade your BLE version to match it.

**Comment by shplume** [comment]
thinks for your help, I downgrade BLE version to v1.33.6 and solved the problem

**Comment by chan150** [comment]
I publish `1.24.20` to fix this issue.

This version limits FBP to `>=1.32.4 <=1.33.6` due to the breaking changes of API.
After I apply latest FBP to this library, the dependencies will be returned.

**Comment by shplume** [comment]
I has been updated to 1.24.20 and solved the problem. Thanks for help.
