### ISSUE TITLE
fix: startScan() doesn't return correct ScanResult

### ISSUE THREAD

**Issue by seungku** [chan150/flutter_blue_plus_windows#25]
**Description**

When startScan() is executed, serviceData of scanResults.listen is not received properly.

**Steps To Reproduce**

1. FlutterBluePlus.startScan()
2. FlutterBluePlus.scanResults.listen(results) { print(results.toString();}
3. print result
flutter: [ScanResult{device: BluetoothDevice{remoteId: AB:CD:EF:00:00:00, platformName: , services: null}, advertisementData: AdvertisementData{advName: , txPowerLevel: null, appearance: null, connectable: true, manufacturerData: {}, serviceData: {}, serviceUuids: [feaa]}, rssi: -60, timeStamp: 2024-11-15 06:24:40.614675}]

**Expected Behavior**

flutter: [ScanResult{device: BluetoothDevice{remoteId: AB:CD:EF:00:00:00, platformName: , services: null}, advertisementData: AdvertisementData{advName: , txPowerLevel: null, appearance: null, connectable: false, manufacturerData: {}, serviceData: {feaa: [32, 0, 14, 130, 25, 0, 6, 199, 253, 58, 25, 12, 50, 8]}, serviceUuids: [feaa]}, rssi: -60, timeStamp: 2024-11-15 06:56:15.442609}]

**Screenshots**

N/A

**Comment by chan150** [comment]
It may work in `1.24.21`.

The implementation is based on below materials:
[1] https://www.bluetooth.com/wp-content/uploads/Files/Specification/HTML/Assigned_Numbers/out/en/Assigned_Numbers.pdf
[2] https://www.bluetooth.org/docman/handlers/DownloadDoc.ashx?doc_id=519976
