### ISSUE TITLE
feat: implement windows using platform channel?

### ISSUE THREAD

**Issue by chipweinberger** [chan150/flutter_blue_plus_windows#3]
see here: https://github.com/boskokg/flutter_blue_plus/issues/6#issuecomment-1932546607

It would be simpler than needing a wrapper IMO.

You would copy the code from WinBle, and alter it to use the Fbp platform channel.

**Comment by stuartmorgan** [comment]
See also https://github.com/flutter/flutter/issues/143095#issuecomment-1933973895 for an argument against this approach.
