### ISSUE TITLE
fix: Write to a characteristic doesn't seem to work

### ISSUE THREAD

**Issue by CamilleBrunin** [chan150/flutter_blue_plus_windows#4]
Is the _write_ to a characteristic supported ?

I can't seem to make it work, whereas it works fine on my android smartphone.

I can however connect to the ble device, and no exception is thrown when I try to write, but then nothing happens.

**Comment by CamilleBrunin** [comment]
UPDATE: I finally understood and fixed my problem!

In the BluetoothCharacteristicWindows class of the library, the "writeWithResponse" parameter of the WinBle write method should be the opposite of the "propertiesWinBle.writeWithoutResponse" value (if false then true, and the other way around). Alternatively, just replace the whole parameter value with the opposite of "withoutResponse" input parameter (cf. image below).

![image](https://github.com/chan150/flutter_blue_plus_windows/assets/56686608/407d77b9-d7d4-42ec-820a-71961c26f6df)

**Comment by chan150** [comment]
I publish the updated code.
Thank you, @CamilleBrunin
