### ISSUE TITLE
fix: Cannot change MTU size on windows.  It is always trying to set MTU to 517.  

### ISSUE THREAD

**Issue by acalpitojr** [chan150/flutter_blue_plus_windows#6]
**Description**

I am trying to connect to a BLE device and negotiate an MTU of 512.  Upon connection, flutter blue seems to always try to set MTU to 517, where I need it to be 512.  

**Steps To Reproduce**

1. await device.connect(mtu: 512);
2. Connects to devices, but negotiates an MTU of 517
3. Try manually setting MTU to 512  await int mtu = device.requestMtu(512);
4. mtu's value is returned as 517, and no MTU request is ever sent to the device.

**Expected Behavior**

requestMtu() function call should negotiate the given mtu with the device.

**Comment by chan150** [comment]
In Windows, we cannot control mtu size.
Instead, we can get max mtu size.

Following this session for more information:
https://github.com/rohitsangwan01/win_ble/issues/8
